
checks:
    python:
        code_rating: true
        duplicate_code: true
        variables_redefined_outer_name: true

tools:
    external_code_coverage:
        timeout: 12000    # Timeout in seconds.
